version: "3.9"
services:
  taipy:
    container_name: sorteggio-kart
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
  nginx:
    container_name: nginx
    image: nginx:1.23
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
