networks:
  network-proxy:
    name: network-proxy
    external: true

services:
  taipy:
    container_name: sorteggio-kart
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: always
